### ISSUE TITLE
Add a very simple webhook

### ISSUE THREAD

**Issue by willbeeching** [jpoehnelt/chrome-meet-webhook-extension#5]
Hey man, this is an awesome plugin!

I'm trying to get it to talk to Homebridge-http-webhooks so I can run a webhook such as: 
http://10.0.0.6:51828/?accessoryId=sensor1&state=true

However the current setup wraps it in a json payload.

Is there any way that I can run the above command changing the true/false at the end when the camera is active/inactive?

TIA!

**Comment by jpoehnelt** [comment]
That shouldn't be too difficult. Does it need to be a `GET` request then?

**Comment by jpoehnelt** [comment]
I'll be publishing https://github.com/jpoehnelt/chrome-meet-webhook-extension/releases/tag/v1.2.2 shortly. It will support webhook urls in the config such as:

`GET https://maker.ifttt.com/trigger/${input.camera === 'active' || input.microphone === 'active' ? 'active'  :  'inactive'}/with/key/somekey`.

which may render to

`GET https://maker.ifttt.com/trigger/active/with/key/somekey`

depending on the state(matches JSON payload).

`POST` is the default method. The extension options page has more information.

**Comment by jpoehnelt** [comment]
Submitted and in review.

**Comment by jpoehnelt** [comment]
@willbeeching  Did you get a chance to try this new version?
